In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from mamba_ssm import Mamba
# from transformers import MambaConfig, MambaForCausalLM, AutoTokenizer


import torch
import numpy as np
import torch
import torch.nn as nn
from torch import tensor
import scipy as sp

# import torchvision
# import torchvision.transforms as transforms

import torch
from torch.utils.data import DataLoader, TensorDataset
from mamba_ssm.modules.block import Block
from functools import partial


from mamba_model import MambaEEG
from mamba_ssm.models.config_mamba import MambaConfig
from models import *

# @TODO SUBJECT SPEFICIC LAYER!!!

In [46]:
!ls

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


task2-NR-2.0-dataset.pickle


In [2]:
import pickle

In [3]:
pic = pickle.load(open('dataset/ZuCo/task2-NR-2.0/pickle/task2-NR-2.0-dataset.pickle','rb'))

In [9]:
pic['YAG'][0]['word'][0]['word_level_EEG']['TRT']

{'TRT_t1': array([1.40261447, 0.90061718, 0.72813612, 0.8450979 , 0.8296752 ,
        0.73214447, 0.58177119, 0.69973809, 0.69607663, 0.57748842,
        0.81024599, 0.73605788, 0.6994341 , 0.56968468, 0.43644938,
        0.3669585 , 1.05047274, 0.6224817 , 0.36138946, 1.32200301,
        0.50691241, 0.41167128, 0.66427219, 0.55471057, 1.079301  ,
        1.08636475, 0.41377681, 0.48100454, 0.64423406, 0.92937535,
        3.37432265, 0.62905771, 0.2836242 , 0.39913288, 0.64353126,
        2.71244669, 2.97693324, 0.47522125, 1.22589278, 0.77576309,
        0.42423472, 0.6610043 , 0.8535791 , 0.96275437, 1.03400195,
        1.1759721 , 0.36638731, 0.61021495, 0.85321581, 0.94697195,
        0.97522181, 0.86939681, 0.6201458 , 0.72206306, 0.91180223,
        0.97550368, 0.81291008, 0.77447575, 0.73569745, 0.69399786,
        1.10057044, 0.35573947, 1.77995169, 1.16867232, 0.87228978,
        0.80914646, 1.13957834, 2.61480427, 1.94425786, 0.54974329,
        0.68824834, 0.75073701, 0.8673

In [68]:
pic['YAG'][0]['sentence_level_EEG']['mean_t1']

array([3.99931383, 1.66266501, 1.1260891 , 1.09210467, 1.11598217,
       1.16841018, 3.06357574, 1.57445288, 1.35179389, 1.15584254,
       1.05645442, 2.63251996, 1.66265202, 1.51152825, 1.20166445,
       1.15183032, 2.94588852, 1.44206679, 1.14164686, 2.10525537,
       1.08507633, 1.03475666, 0.9827835 , 1.16995919, 1.71615124,
       1.6393292 , 0.83065325, 0.8150444 , 1.01834726, 1.50741231,
       3.38615656, 0.89979148, 0.76764631, 0.80608618, 1.13148689,
       3.05741453, 2.91894507, 1.12165987, 1.34454691, 1.18896484,
       1.43577671, 1.08912849, 1.27571881, 1.45165181, 1.57095182,
       1.70521653, 2.478441  , 1.17878437, 1.39465129, 1.42945838,
       1.50007725, 1.53819156, 1.2499299 , 1.34544313, 1.56442928,
       1.61160123, 1.46748006, 1.64660895, 1.65201652, 1.5647397 ,
       1.77583063, 1.7138586 , 1.79244626, 1.60919929, 1.29906607,
       1.14817905, 1.429672  , 2.11905003, 2.20650697, 1.84685791,
       1.49745357, 0.8277719 , 0.68556255, 2.10811996, 1.81952

In [63]:
for key in pic.keys():
    try:
        print(pic[key][0]['sentence_level_EEG'].keys())
    except:
        continue

dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])
dict_keys(['mean_t1', 'mean_t2', 'mean_a1', 'mean_a2', 'mean_b1', 'mean_b2', 'mean_g1', 'mean_g2'])


In [58]:
pic['YAK'][2].keys()

dict_keys(['content', 'sentence_level_EEG', 'word', 'word_tokens_has_fixation', 'word_tokens_with_mask', 'word_tokens_all'])

In [20]:
model_name = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(model_name)

encoder = HuggingFaceEncoder(model_name)


mm = MambaConfig(ssm_cfg = {'layer':'Mamba1'}, d_model = 64)

ee = EEGEncoder(mamba_config=mm, embedding = 'last').cuda()

In [26]:
test = torch.rand((1,20, 22)).cuda()
inputs = tokenizer(["This is a sentence"], return_tensors='pt', padding=True, truncation=True)

In [30]:
# inputs.to('cuda')

In [35]:
etc = EEGTextCLIP(ee, encoder).cuda()

In [36]:
# torch.tensor("This is a sentence")

In [39]:
etc(test, inputs.to('cuda'))

(tensor([[ 0.1636,  3.0080, -0.1541,  ...,  0.7479, -0.4782, -0.1189]],
        device='cuda:0', grad_fn=<NativeLayerNormBackward0>),
 tensor([[-0.0857, -0.5431, -0.4438,  ..., -0.4187, -0.6993,  1.0623]],
        device='cuda:0', grad_fn=<NativeLayerNormBackward0>))

In [6]:



# Example Usage
model_name = 'bert-base-uncased'
encoder = HuggingFaceEncoder(model_name)

# For sentences
sentences = ["This is a sentence.", "Here is another one."]
sentence_embeddings = encoder.process_sentences(sentences, pooling='mean')
print("Sentence embeddings:", sentence_embeddings)


Sentence embeddings: tensor([[[ 0.0884, -0.1475,  0.1752,  ..., -0.0535, -0.1021,  0.5540]],

        [[ 0.1275, -0.2232,  0.1702,  ..., -0.0162,  0.0776,  0.1723]]],
       grad_fn=<StackBackward0>)


In [7]:
sentence_embeddings.shape

torch.Size([2, 1, 768])